# Application name
spring.application.name=pos

# Swagger/OpenAPI settings
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# MySQL database config
spring.datasource.url=jdbc:mysql://localhost:3306/pos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.io.swagger.v3=DEBUG